# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_org',
            new_name='courseorg',
        ),
    ]
